### ISSUE TITLE
Handle content main file no longer existing

### ISSUE THREAD

**Issue by jameslibscie** [p2pcommons/sdk-js#121]
**User story**
As a content creator
I want the validity of my content to be checked
so that I don't publish or share content that isn't readable

**Acceptance criteria**
- [x] There is a way to verify that the `main` file exists

**Suggestion**
Include this check in the `validate()` method, so that it gets called upon creation and publishing automatically.

**Comment by dpaez** [comment]
When I was doing this task I started to think about the `init` case. Probably this goes into the specs repo but I just want to confirm this, when a user creates a new module, since they don't know beforehand the directory name (it doesn't exist yet) they can put the `main` file inside. So, the validate should skip the init case. After init, if the user decides to `set` a new main file the validation then at that point is the validation step is expected.

**Comment by jameslibscie** [comment]
@dpaez If there is no `main` file specified, the module is still valid. Only if the `main` file is specified, but does not exist, is the module invalid. I should have spec'd this clearer. Is this how this is implemented?

**Comment by dpaez** [comment]
@jameslibscie Yes, that's what I try to accomplish. At the beginning (`init`) it doesn't make sense to indicate the main file. But after that step if one wants to indicate a main file, then you can use `set` for this, and the validation will check if the file exists.
