### ISSUE TITLE
New clone method

### ISSUE THREAD

**Issue by dpaez** [p2pcommons/sdk-js#40]
## Context:

@chartgerink I just revisited this and I think we are a bit "restricted" to save a new "external" module, this is because two things:
1. `init` method currently does not accept an `url` or key as a param. An external module would already have a url.
2. `set` method can't modify the url. This is a restricted param. users can only update certain params. I guess I can add a `force` param to accomplish this but I'm open for suggestions.

_Originally posted by @dpaez in https://github.com/p2pcommons/sdk-js/pull/25_

## Possible solution

Add a new method `clone` which can overcome this and can create new modules from external (already created) keys. 

**needs more discussion**

**Comment by jameslibscie** [comment]
What do we need the clone method for? Are there (important) Hypergraph features that depend on this? If so, which ones?

**Comment by chartgerink** [comment]
The clone method is necessary for all the features that require some form of networking or module validation, e.g., pulling in parent content modules, other people's profiles, etc. 

This means that anything that relates to *any* module that one didn't directly create requires the clone method. It's similar to `git clone` in that sense --- if it's not local already we need to get the info.

Most importantly, if someone tries to publish (previously register) a module that they don't own but received the Dat key for, we need to clone to verify that the module at that version is a valid one. This method is also needed for the Vault (because it's our cloning machine so to speak).

**Comment by dpaez** [comment]
Super complete reply @chartgerink, thank you very much!

**Comment by dpaez** [comment]
I'm adding this here as a reminder 😄 

In the PR #63  I've added a new internal method called [`_getModule`](https://github.com/p2pcommons/sdk-js/blob/f9ad588897e25c90e04d228aa3e56b216dd1eb2e/index.js#L660) that can be seen as a _clone_. At least I think we can use that method as the foundation for clone. Only tests would be needed.

**Comment by jameslibscie** [comment]
Thanks!
